# Description: This workflow tests environments split changes for POC purposes.
#              It will be reverted before changes are merged onto `main`.

name: POC / Split environments

concurrency:
  group: e2e-${{ github.event.pull_request.id }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [split-environments/main]
    types: [opened, synchronize, labeled]

permissions:
  pull-requests: write # used to remove label
  # other permissions are defaulted to "none"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Add Amplify CLI
        run: yarn global add @aws-amplify/cli

      - name: Pull down Geo AWS environments, on cache miss
        run: yarn environments geo pull
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_GEO }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_GEO }}

      - name: Pull down Datastore AWS environments, on cache miss
        run: yarn environments datastore pull
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DATASTORE }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DATASTORE }}

      # new pull-environments.sh tests
      - name: Pull phone environments only
        run: yarn environments auth pull:phone
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Pull all auth environments except phone
        run: yarn environments auth pull:non-phone
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
