# Description: This workflow runs unit + e2e tests, then publishes UI packages
#              to `@next-release` NPM tag.
#
# Triggered by: merge to `next-release/run-react-18-ci`

name: Test and Publish / next-release

on:
  push:
    branches: [next-release/run-react-18-ci]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  setup-cache:
    uses: aws-amplify/amplify-ui/.github/workflows/reusable-setup-cache.yml@next-release/run-react-18-ci
    with:
      commit: ${{ github.sha }}
      repository: ${{ github.repository }}

  unit:
    uses: aws-amplify/amplify-ui/.github/workflows/reusable-unit.yml@next-release/run-react-18-ci
    needs: setup-cache
    with:
      commit: ${{ github.sha }}
      repository: ${{ github.repository }}

  e2e:
    uses: aws-amplify/amplify-ui/.github/workflows/reusable-e2e.yml@next-release/run-react-18-ci
    needs: unit
    with:
      commit: ${{ github.sha }}
      repository: ${{ github.repository }}
    secrets:
      AUTH_E2E_ROLE_ARN: ${{ secrets.AUTH_E2E_ROLE_ARN }}
      DATASTORE_E2E_ROLE_ARN: ${{ secrets.DATASTORE_E2E_ROLE_ARN }}
      GEO_E2E_ROLE_ARN: ${{ secrets.GEO_E2E_ROLE_ARN }}
      STORAGE_E2E_ROLE_ARN: ${{ secrets.STORAGE_E2E_ROLE_ARN }}
      LIVENESS_E2E_ROLE_ARN: ${{ secrets.LIVENESS_E2E_ROLE_ARN }}
      IN_APP_MESSAGING_E2E_ROLE_ARN: ${{ secrets.IN_APP_MESSAGING_E2E_ROLE_ARN }}
      DOMAIN: ${{ secrets.DOMAIN }}
      PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
      USERNAME: ${{ secrets.USERNAME }}
      NEW_PASSWORD: ${{ secrets.NEW_PASSWORD }}
      VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
      SITE_URL: ${{ secrets.SITE_URL }}
      DOCSEARCH_DOCS_APP_ID: ${{ secrets.DOCSEARCH_DOCS_APP_ID }}
      DOCSEARCH_DOCS_API_KEY: ${{ secrets.DOCSEARCH_DOCS_API_KEY }}
      DOCSEARCH_DOCS_INDEX_NAME: ${{ secrets.DOCSEARCH_DOCS_INDEX_NAME }}

  publish:
    needs: [e2e]
    uses: ./.github/workflows/reusable-tagged-publish.yml
    with:
      dist-tag: react-18
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-test:
    needs: publish
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout repo
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
      - name: Setup Node.js 18
        # uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0 https://github.com/actions/setup-node/commit/64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        uses: actions/setup-node@6e9e44895f11c5489716beba7b3be1cd4d76f8e9 # v3.4.1 https://github.com/actions/setup-node/commit/6e9e44895f11c5489716beba7b3be1cd4d76f8e9
        with:
          node-version: 18.18.2
          cache: 'yarn'
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
      - name: Add Amplify CLI
        run: yarn global add @aws-amplify/cli
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.AUTH_E2E_ROLE_ARN }}
      # Amplify CLI does not support headless pull with temporary credentials
      # when useProfile is false.
      # See: https://github.com/aws-amplify/amplify-cli/issues/11009.
      - name: Create temp AWS profile
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && \
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && \
          aws configure set aws_session_token $AWS_SESSION_TOKEN && \
          aws configure set default.region $AWS_REGION
      - name: Pull down AWS environments
        run: yarn pull
        working-directory: ./canary
      - name: Delete AWS Profile
        run: rm -rf ~/.aws
      - name: Setup canary apps against @next-release
        run: yarn setup:next-release
        working-directory: ./canary
      - name: Run yarn install on each sample app
        run: yarn install
        working-directory: ./canary
      - name: Run yarn build on each sample app
        run: yarn build
        working-directory: ./canary
