name: Publish to @liveness

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Liveness Tests']
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ci
    permissions:
      id-token: write
      contents: write
    # We only publish if the previous workflow run (Tests) was successful
    # and the previous workflow was called from main branch.
    #
    # Note that we check against workflow_run.head_branch instead of github.ref
    # because workflow_run is always run on main, even if it's triggered from
    # another branch.
    #
    # https://github.community/t/workflow-run-not-working-as-expected/139342
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'liveness-main')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: 'liveness-main'

      - name: Configure CodeArtifact
        id: configure-codeartifact
        uses: ./.github/actions/codeartifact-action
        with:
          role-to-assume: ${{ secrets.LIVENESS_DEPLOYMENT_ROLE }}
          domain: amplify-ui-liveness
          repository: amplify-ui

      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
          registry-url: ${{ steps.configure-codeartifact.outputs.repository-endpoint }}
          always-auth: true

      - name: Install packages
        run: yarn --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ steps.configure-codeartifact.outputs.repository-token }}

      - name: Add changeset that bumps all public packages
        # There needs to be a changeset for @aws-amplify/ui[-framework] to publish.
        run: cp .github/changeset-presets/bump-versions.md .changeset

      - name: Run changeset version to liveness tag
        run: yarn version:liveness
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # CodeArtifact
      - name: Publish to liveness tag for CodeArtifact
        run: yarn publish:liveness
        env:
          NPM_AUTH_TOKEN: ${{ steps.configure-codeartifact.outputs.repository-token }}

      # Verdaccio
      - name: Login to Verdaccio
        run: |
          VERDACCIO_REGISTRY=registry.edge.reventlov.rekognition.aws.dev

          yarn config set registry https://$VERDACCIO_REGISTRY
          echo "//$VERDACCIO_REGISTRY/:_authToken=$NPM_TOKEN" >> .npmrc
          echo "//$VERDACCIO_REGISTRY/:always-auth=true" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.LIVENESS_VERDACCIO_TOKEN }}
      - name: Publish to liveness tag for Verdaccio
        run: yarn publish:liveness
