# Description: this is a reusable workflow that sets up cache for unit and e2e tests.
# It checks if caches exist and populates them if missing, so downstream jobs can restore them.

on:
  workflow_call:
    inputs:
      commit:
        # commit to run tests against
        required: true
        type: string
      repository:
        # repository to run tests against (possibly a fork of amplify-ui)
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.1.3 https://github.com/actions/checkout/commit/cd7d8d697e10461458bc61a30d094dc601a8b017
        with:
          ref: ${{ inputs.commit }}
          repository: ${{ inputs.repository }}
          persist-credentials: false
      - name: Setup Node.js 20
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v4.0.2 https://github.com/actions/setup-node/commit/60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 20
          cache: 'yarn'
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
      - name: Check if Cypress cache exists
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        id: check-cypress-cache
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('yarn.lock') }}
          lookup-only: true
      - name: Check if Puppeteer cache exists
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        id: check-puppeteer-cache
        with:
          path: ~/.cache/puppeteer
          key: ${{ runner.os }}-puppeteer-${{ hashFiles('yarn.lock') }}
          lookup-only: true
      - name: Check if node_modules cache exists
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        id: check-node-modules-cache
        with:
          path: |
            ./node_modules
            **/node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('yarn.lock') }}
          lookup-only: true
      - name: Install packages
        if: steps.check-node-modules-cache.outputs.cache-hit != 'true'
        uses: ./.github/actions/install-with-retries
        with:
          skip-cypress-binary: ${{ steps.check-cypress-cache.outputs.cache-hit }}
      - name: Cache node_modules
        if: steps.check-node-modules-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: |
            ./node_modules
            **/node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('yarn.lock') }}
      - name: Cache Cypress
        if: steps.check-cypress-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('yarn.lock') }}
      - name: Cache Puppeteer
        if: steps.check-puppeteer-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.cache/puppeteer
          key: ${{ runner.os }}-puppeteer-${{ hashFiles('yarn.lock') }}
