# Description: This workflow runs unit + e2e tests on PRs
#   targeting `account-settings/main`.
#
# Triggered by:
#   (1) maintainer pushes a commit to PRs targeting those branches.

name: Test / Account Settings / PRs

concurrency:
  group: e2e-accountsettings-${{ github.event.pull_request.id }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [account-settings/main]
    types: [opened, synchronize]

jobs:
  test:
    uses: aws-amplify/amplify-ui/.github/workflows/reusable-e2e.yml@account-settings/main
    with:
      commit: ${{ github.event.pull_request.head.sha }}
      repository: ${{ github.event.pull_request.head.repo.full_name }}
    secrets:
      AUTH_E2E_ROLE_ARN: ${{ secrets.AUTH_E2E_ROLE_ARN }}
      DATASTORE_E2E_ROLE_ARN: ${{ secrets.DATASTORE_E2E_ROLE_ARN }}
      GEO_E2E_ROLE_ARN: ${{ secrets.GEO_E2E_ROLE_ARN }}
      STORAGE_E2E_ROLE_ARN: ${{ secrets.STORAGE_E2E_ROLE_ARN }}
      IN_APP_MESSAGING_E2E_ROLE_ARN: ${{ secrets.IN_APP_MESSAGING_E2E_ROLE_ARN }}
      DOMAIN: ${{ secrets.DOMAIN }}
      PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
      USERNAME: ${{ secrets.USERNAME }}
      NEW_PASSWORD: ${{ secrets.NEW_PASSWORD }}
      VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
      SITE_URL: ${{ secrets.SITE_URL }}
      DOCSEARCH_DOCS_APP_ID: ${{ secrets.DOCSEARCH_DOCS_APP_ID }}
      DOCSEARCH_DOCS_API_KEY: ${{ secrets.DOCSEARCH_DOCS_API_KEY }}
      DOCSEARCH_DOCS_INDEX_NAME: ${{ secrets.DOCSEARCH_DOCS_INDEX_NAME }}
