# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  unit:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        package:
          - '@aws-amplify/ui'
          - '@aws-amplify/ui-angular'
          - '@aws-amplify/ui-vue'
          - '@aws-amplify/ui-react'

    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@v2

      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Lint packages
        run: yarn workspace ${{ matrix.package }} lint

      - name: Build ${{ matrix.package }} package
        run: yarn workspace ${{ matrix.package }} build

      - name: Run ${{ matrix.package }} tests
        run: yarn workspace ${{ matrix.package}} test

  e2e:
    # Only run e2e tests if unit tests pass
    needs: unit
    runs-on: ubuntu-latest
    environment: ci
    env:
      NODE_ENV: test

    strategy:
      # Run each examples (e.g. `next-example`) which uses a library (e.g. `@aws-amplify/ui-react`)
      # BUT, Exclude `@skip` tests in `main` and exclude `@todo-${{ framework }}` tests in PRs
      # See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix
      matrix:
        include:
          - framework: angular
            tags: '@angular and not (@skip or @todo-angular)'

          - framework: next
            tags: '@react and not (@skip or @todo-react)'

          - framework: vue
            tags: '@vue and not (@skip or @todo-vue)'

    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@v2

      - name: Next.js Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Add Amplify CLI
        run: yarn global add @aws-amplify/cli@beta

      - name: Pull down AWS environments
        run: yarn environments pull
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build ${{ matrix.framework }} example
        run: yarn workspace ${{ matrix.framework }}-example build

      - name: Start ${{ matrix.framework }} example
        run: yarn workspace ${{ matrix.framework }}-example start & npx wait-on -c waitOnConfig.json -t 20000 http-get://localhost:3000/ui/components/authenticator/sign-in-with-username

      - name: Run E2E tests against ${{ matrix.framework }} example
        run: yarn workspace e2e test
        env:
          # Override on the default value in `cypress.json` with framework-specific tag
          TAGS: '${{ matrix.tags }}'

          # Env values for testing flows
          DOMAIN: ${{ secrets.DOMAIN }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          USERNAME: ${{ secrets.USERNAME }}
          NEW_PASSWORD: ${{ secrets.NEW_PASSWORD }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
  docs:
    # Only run docs tests if e2e tests pass
    needs: e2e
    runs-on: ubuntu-latest
    environment: ci
    env:
      NODE_ENV: test
    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@v2

      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build docs package
        run: yarn docs build
